spring:
  cache:
    cache-names:
    - rate-limit-buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s
        
bucket4j:
  enabled: true
  filters:
  - cache-name: rate-limit-buckets
    url: .*
    strategy: first
    http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"You have exhausted your API Request Quota\" }"
    rate-limits:
    - expression: "getRemoteAddr()"
      bandwidths:
      - capacity: 10000
        time: 1
        unit: hours
      